/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./*.{js,ts,jsx,tsx}"
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c0c1ff",
        "primary-fixed": "#63f7ff",
        "primary-fixed-dim": "#00dce5",
        "on-secondary-container": "#b0b2ff",
        "outline": "#849495",
        "on-secondary-fixed": "#07006c",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "secondary": "#c0c1ff",
        "tertiary": "#fff9f0",
        "inverse-primary": "#00696e",
        "surface-container-lowest": "#0e0e13",
        "secondary-container": "#3131c0",
        "surface-dim": "#131318",
        "surface-container": "#1f1f24",
        "on-primary": "#003739",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-bright": "#39393e",
        "on-tertiary": "#3a3000",
        "surface-container-highest": "#35343a",
        "surface-tint": "#00dce5",
        "on-surface": "#e4e1e8",
        "tertiary-container": "#ffdb3f",
        "on-background": "#e4e1e8",
        "on-tertiary-fixed": "#221b00",
        "surface-container-low": "#1b1b20",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#e7c427",
        "on-primary-container": "#006c71",
        "on-surface-variant": "#b9caca",
        "primary": "#e9feff",
        "surface": "#131318",
        "error": "#ffb4ab",
        "on-primary-fixed": "#002021",
        "surface-variant": "#35343a",
        "primary-container": "#00f5ff",
        "inverse-surface": "#e4e1e8",
        "background": "#131318",
        "inverse-on-surface": "#303035",
        "on-secondary": "#1000a9",
        "outline-variant": "#3a494a",
        "on-tertiary-container": "#736000",
        "secondary-fixed": "#e1e0ff",
        "on-tertiary-fixed-variant": "#544600",
        "surface-container-high": "#2a292f",
        "on-primary-fixed-variant": "#004f53",
        "tertiary-fixed": "#ffe16c"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
};
