/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./*.{js,ts,jsx,tsx}"
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-container": "#2c3ea3",
        "on-surface-variant": "#bac9cc",
        "on-secondary-fixed": "#00105c",
        "on-tertiary-fixed-variant": "#7b008f",
        "surface-container-highest": "#35343a",
        "on-secondary-container": "#a8b4ff",
        "primary-fixed-dim": "#00daf3",
        "on-tertiary-container": "#941da8",
        "on-tertiary": "#570066",
        "tertiary-fixed": "#ffd6fe",
        "on-primary-fixed": "#001f24",
        "on-primary-fixed-variant": "#004f58",
        "surface-tint": "#00daf3",
        "primary-container": "#00e5ff",
        "inverse-on-surface": "#303036",
        "surface-dim": "#131318",
        "primary-fixed": "#9cf0ff",
        "surface-container": "#1f1f25",
        "outline-variant": "#3b494c",
        "secondary-fixed-dim": "#bac3ff",
        "surface-container-high": "#2a292f",
        "inverse-surface": "#e4e1e9",
        "on-secondary-fixed-variant": "#293ca0",
        "on-secondary": "#08218a",
        "on-surface": "#e4e1e9",
        "error": "#ffb4ab",
        "on-background": "#e4e1e9",
        "on-primary": "#00363d",
        "tertiary-fixed-dim": "#f9abff",
        "primary": "#c3f5ff",
        "surface-container-low": "#1b1b20",
        "on-primary-container": "#00626e",
        "tertiary": "#ffe5fc",
        "error-container": "#93000a",
        "tertiary-container": "#fcbbff",
        "background": "#131318",
        "on-error": "#690005",
        "secondary": "#bac3ff",
        "surface-variant": "#35343a",
        "surface": "#131318",
        "surface-bright": "#39383e",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#dee0ff",
        "on-tertiary-fixed": "#35003f",
        "inverse-primary": "#006875",
        "outline": "#849396",
        "surface-container-lowest": "#0e0e13"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
};
